name: build eclipse plugins

on:
    workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build_bare_linux_windows:
    name: baremetal for ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]
    env: 
      CC: gcc-8
      CXX: g++-8

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Install Dependencies on Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
          sudo apt-get install openjdk-8-jdk
          wget https://mirrors.tuna.tsinghua.edu.cn/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
          sudo mv apache-maven-3.6.3-bin.tar.gz /usr/local/
          cd /usr/local/
          sudo tar -zxvf apache-maven-3.6.3-bin.tar.gz
          source /etc/profile
    - name: Build
      run: |
        cd /runner/work/eclipse-plugins.git
        mvn clean verify
    - name: Upload files artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: ilg.gnumcueclipse.repository
        # A file, directory or wildcard pattern that describes what to upload
        path: ilg.gnumcueclipse.repository.tar.gz
